One niv-update action to rule them all

diff --git a/.github/workflows/niv-update.yml b/.github/workflows/niv-update.yml
--- a/.github/workflows/niv-update.yml
+++ b/.github/workflows/niv-update.yml
@@ -8,9 +8,10 @@ on:
 jobs:
   niv-update:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        source: [ nixpkgs, crate2nix, nix-test-runner ]
+    env:
+      # Results in crate2nix being updated every hour!
+      # - crate2nix
+      sources: nixpkgs nix-test-runner cargo-release nixpkgs-mozilla cachix
     steps:
       - uses: actions/checkout@v2
       - uses: cachix/install-nix-action@v8
@@ -20,30 +21,59 @@ jobs:
           signingKey: '${{ secrets.CACHING_SIGNING_KEY }}'
       - run: nix-env -iA nixpkgs.niv
       - run: nix-env -iA nixpkgs.crate2nix
-      - run: niv update ${{matrix.source}}
-      - name: Build and push changes
+      - name: Update each source and push changes
         run: |
-          if test -n "$(git status --porcelain)"; then
-            nix build -L -f ./ci.nix buildPkgs
-            git config --local user.email 'info@eigenvalue.net'
-            git config --local user.name 'Peter Kolloch, Bot'
-            n=0
-            until [ $n -ge 5 ]
-            do
-              git fetch
-              git reset --hard origin/master
-              # Do the update again to prevent merge conflicts
-              niv update ${{matrix.source}}
+          failed=""
+
+          for source in $sources; do
+            git fetch origin master
+            git reset --hard origin/master
+            niv update $source
+            if test -n "$(git status --porcelain)"; then
               (
                 set -x
-                cd pkgs/rust/generated
-                crate2nix generate
+                git --no-pager diff HEAD
+                git config --local user.email 'info@eigenvalue.net'
+                git config --local user.name 'Peter Kolloch, Bot'
+                n=0
+                until [ $n -ge 5 ]
+                do
+                  (
+                    cd pkgs/rust/generated
+                    crate2nix generate
+                  ) || {
+                    echo "Regenerating Cargo.nix failed."
+                    failed="$failed $source"
+                    break
+                  }
+                  git commit -m 'niv update: updated $source' -a
+
+                  nix build -f . -L buildPkgs || {
+                    echo "Building packages failed. Skip updating $source."
+                    failed="$failed $source"
+                    break
+                  }
+                  git push && break
+                  n=$[$n+1]
+                  sleep 1
+                  # Another try
+                  git fetch
+                  git reset --hard origin/master
+                  niv update $source
+                done
+                if [ $n -ge 5 ]; then
+                  echo "gave up after 5 tries"
+                  exit 1
+                fi
               )
-              git commit -m 'niv update ${{matrix.source}}' -a
-              git push && break
-              n=$[$n+1]
-              sleep 1
-            done
-          else
-            echo no changes
+            else
+              echo "no change for $source"
+            fi
+          done
+
+          if [ -n "$failed" ]; then
+            echo "The following sources couldn't be updated "
+            echo "because of test failures:"
+            echo "$failed"
+            exit 3
           fi
